//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\gitest\410proj\application\fcfsetting.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: yibo
//              Version: NX 7.5
//              Date: 09-04-2012  (Format: mm-dd-yyyy)
//              Time: 12:39 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class fcfsetting
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    public static fcfsetting thefcfsetting;
    public static pubfun thefun = new pubfun();
    private string theDialogName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.UIBlock group0;// Block type: Group
    private NXOpen.BlockStyler.UIBlock tolatt;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock framstyle;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock double0;// Block type: Double
    private NXOpen.BlockStyler.UIBlock valuestyle;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock matrstyle;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock group;// Block type: Group
    private NXOpen.BlockStyler.UIBlock mainbase;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock maiinbasemat;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock separator0;// Block type: Separator
    private NXOpen.BlockStyler.UIBlock separator01;// Block type: Separator
    private NXOpen.BlockStyler.UIBlock ifotherbase;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock separator02;// Block type: Separator
    private NXOpen.BlockStyler.UIBlock firstrefbase;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock firstrefbasemat;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock separator03;// Block type: Separator
    private NXOpen.BlockStyler.UIBlock secrefbase;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock secrefbasemat;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock group1;// Block type: Group
    private NXOpen.BlockStyler.UIBlock double01;// Block type: Double
    private NXOpen.BlockStyler.UIBlock toggle0;// Block type: Toggle
    private NXOpen.BlockStyler.UIBlock selection01;// Block type: Selection
    private NXOpen.BlockStyler.UIBlock postion;// Block type: Enumeration
    private NXOpen.BlockStyler.UIBlock selection0;// Block type: Selection
    private NXOpen.BlockStyler.UIBlock point0;// Block type: Specify Point
    public NXOpen.TaggedObject[] plcpoint;//放置点
    private NXOpen.BlockStyler.UIBlock double02;// Block type: Double
    public Point theplcpoint = null;
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int              SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int                 SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int           SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int                 SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int                 SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int             SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int             SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int                SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int            SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int            SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int             SnapPointTypesEnabled_PointonCurve = (1 <<10);
    public static readonly int           SnapPointTypesEnabled_PointonSurface = (1 <<11);
    public static readonly int         SnapPointTypesEnabled_PointConstructor = (1 <<12);
    public static readonly int     SnapPointTypesEnabled_TwocurveIntersection = (1 <<13);
    public static readonly int             SnapPointTypesEnabled_TangentPoint = (1 <<14);
    public static readonly int                    SnapPointTypesEnabled_Poles = (1 <<15);
    public static readonly int         SnapPointTypesEnabled_BoundedGridPoint = (1 <<16);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int          SnapPointTypesOnByDefault_UserDefined = (1 << 0);
    public static readonly int             SnapPointTypesOnByDefault_Inferred = (1 << 1);
    public static readonly int       SnapPointTypesOnByDefault_ScreenPosition = (1 << 2);
    public static readonly int             SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int             SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int         SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int         SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int            SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int        SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int        SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int         SnapPointTypesOnByDefault_PointonCurve = (1 <<10);
    public static readonly int       SnapPointTypesOnByDefault_PointonSurface = (1 <<11);
    public static readonly int     SnapPointTypesOnByDefault_PointConstructor = (1 <<12);
    public static readonly int SnapPointTypesOnByDefault_TwocurveIntersection = (1 <<13);
    public static readonly int         SnapPointTypesOnByDefault_TangentPoint = (1 <<14);
    public static readonly int                SnapPointTypesOnByDefault_Poles = (1 <<15);
    public static readonly int     SnapPointTypesOnByDefault_BoundedGridPoint = (1 <<16);
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public fcfsetting()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDialogName = "fcfsetting.dlx";
            theDialog = theUI.CreateDialog(theDialogName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddFocusNotifyHandler(new NXOpen.BlockStyler.BlockDialog.FocusNotify(focusNotify_cb));
            theDialog.AddKeyboardFocusNotifyHandler(new NXOpen.BlockStyler.BlockDialog.KeyboardFocusNotify(keyboardFocusNotify_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        try
        {
            thefcfsetting = new fcfsetting();
            // The following method shows the dialog immediately
            thefcfsetting.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            thefcfsetting.Dispose();
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static int UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //This method shows the dialog on the screen
    //------------------------------------------------------------------------------
    public NXOpen.UIStyler.DialogResponse Show()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("group0");
            tolatt = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("tolatt");
            framstyle = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("framstyle");
            double0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("double0");
            valuestyle = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("valuestyle");
            matrstyle = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("matrstyle");
            group = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("group");
            mainbase = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("mainbase");
            maiinbasemat = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("maiinbasemat");
            separator0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("separator0");
            separator01 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("separator01");
            ifotherbase = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("ifotherbase");
            separator02 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("separator02");
            firstrefbase = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("firstrefbase");
            firstrefbasemat = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("firstrefbasemat");
            separator03 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("separator03");
            secrefbase = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("secrefbase");
            secrefbasemat = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("secrefbasemat");
            group1 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("group1");
            double01 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("double01");
            toggle0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("toggle0");
            selection01 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("selection01");
            postion = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("postion");
            selection0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("selection0");
            point0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("point0");
            double02 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("double02");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            selection01.GetProperties().SetLogical("Enable", false);
            ifotherbase.GetProperties().SetEnum("Value", 0);
            firstrefbase.GetProperties().SetLogical("Enable", false);
            firstrefbasemat.GetProperties().SetLogical("Enable", false);
            secrefbase.GetProperties().SetLogical("Enable", false);
            secrefbasemat.GetProperties().SetLogical("Enable", false);
            toggle0.GetProperties().SetLogical("Value", false);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if(block == tolatt)
            {
            //---------Enter your code here-----------
            }
            else if(block == framstyle)
            {
            //---------Enter your code here-----------
            }
            else if(block == double0)
            {
            //---------Enter your code here-----------
            }
            else if(block == valuestyle)
            {
            //---------Enter your code here-----------
            }
            else if(block == matrstyle)
            {
            //---------Enter your code here-----------
            }
            else if(block == mainbase)
            {
            //---------Enter your code here-----------
            }
            else if(block == maiinbasemat)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator0)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator01)
            {
            //---------Enter your code here-----------
            }
            else if(block == ifotherbase)
            {
                int m = ifotherbase.GetProperties().GetEnum("Value");
                if (m == 0)
                {
                    firstrefbase.GetProperties().SetLogical("Enable", false);
                    firstrefbasemat.GetProperties().SetLogical("Enable", false);
                    secrefbase.GetProperties().SetLogical("Enable", false);
                    secrefbasemat.GetProperties().SetLogical("Enable", false);
                }
                else if (m == 1)
                {
                    firstrefbase.GetProperties().SetLogical("Enable", true);
                    firstrefbasemat.GetProperties().SetLogical("Enable", true);
                    secrefbase.GetProperties().SetLogical("Enable", false);
                    secrefbasemat.GetProperties().SetLogical("Enable", false);
                }
                else if (m == 2)
                {
                    firstrefbase.GetProperties().SetLogical("Enable", true);
                    firstrefbasemat.GetProperties().SetLogical("Enable", true);
                    secrefbase.GetProperties().SetLogical("Enable", true);
                    secrefbasemat.GetProperties().SetLogical("Enable", true);

                }
            //---------Enter your code here-----------
            }
            else if(block == separator02)
            {
            //---------Enter your code here-----------
            }
            else if(block == firstrefbase)
            {
            //---------Enter your code here-----------
            }
            else if(block == firstrefbasemat)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator03)
            {
            //---------Enter your code here-----------
            }
            else if(block == secrefbase)
            {
            //---------Enter your code here-----------
            }
            else if(block == secrefbasemat)
            {
            //---------Enter your code here-----------
            }
            else if(block == double01)
            {
            //---------Enter your code here-----------
            }
            else if(block == toggle0)
            {
                if (toggle0.GetProperties().GetLogical("Value"))
                {
                    selection01.GetProperties().SetLogical("Enable", true);
                }
                else if (!toggle0.GetProperties().GetLogical("Value"))
                {
                    selection01.GetProperties().SetLogical("Enable", false);
                }
            //---------Enter your code here-----------
            }
            else if(block == selection01)
            {
            //---------Enter your code here-----------
            }
            else if(block == postion)
            {
            //---------Enter your code here-----------
            }
            else if(block == selection0)
            {
            //---------Enter your code here-----------
            }
            else if(block == point0)
            {
                plcpoint = point0.GetProperties().GetTaggedObjectVector("SelectedObjects");
                theplcpoint = Tag2NXObject<Point>(plcpoint[0].Tag);
                Point3d pt3d = theplcpoint.Coordinates;//这个就是放置点
                string attvalue = tolatt.GetProperties().GetEnumAsString("Value");
                object attrtype = null;//这个是公差类型
                switch (attvalue)
                {
                    case "直线度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Straightness;
                        break;
                    case "平面度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Flatness;

                        break;
                    case "圆度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Circularity;
                        break;
                    case "圆柱度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Cylindricity;
                        break;
                    case "直线轮廓":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.ProfileOfALine;
                        break;
                    case "曲面轮廓":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.ProfileOfASurface;
                        break;
                    case "倾斜度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Angularity;
                        break;
                    case "垂直度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Perpendicularity;
                        break;
                    case "平行度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Parallelism;
                        break;
                    case "位置":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Position;
                        break;
                    case "对称度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Symmetry;
                        break;
                    case "同轴度":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.Concentricity;
                        break;
                    case "圆跳动":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.CircularRunout;
                        break;
                    case "全跳动":
                        attrtype = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic.TotalRunout;
                        break;

                }
                int i = valuestyle.GetProperties().GetEnum("Value");
                object zhileixing = null;//这个是公差的值类型，可以是fai,Sfai.
                if (i == 0)
                {
                    zhileixing = NXOpen.Annotations.FeatureControlFrameDataBuilder.ToleranceZoneShape.Diameter;
                }
                else if (i == 1)
                {
                    zhileixing = NXOpen.Annotations.FeatureControlFrameDataBuilder.ToleranceZoneShape.None;
                }
                else if (i == 2)
                {
                    zhileixing = NXOpen.Annotations.FeatureControlFrameDataBuilder.ToleranceZoneShape.SphericalDiameter;
                }
                object matcondition = null;//行为公差的材料状况
                //string matconditionatt =  .GetProperties().GetEnumAsString("Value");
                string matconditionatt = matrstyle.GetProperties().GetEnumAsString("Value");
                if (matconditionatt == "最好材料状况")
                {
                    matcondition = NXOpen.Annotations.FeatureControlFrameDataBuilder.ToleranceMaterialModifier.MaximumMaterialCondition;
                }
                else if (matconditionatt == "最差材料状况")
                {
                    matcondition = NXOpen.Annotations.FeatureControlFrameDataBuilder.ToleranceMaterialModifier.LeastMaterialCondition;
                }
                else if (matconditionatt == "不考虑特征大小")
                {
                    matcondition = NXOpen.Annotations.FeatureControlFrameDataBuilder.ToleranceMaterialModifier.RegardlessOfFeatureSize;
                }
                else if (matconditionatt == "无")
                {
                    matcondition = null;
                }
                    string baseattstr = mainbase.GetProperties().GetEnumAsString("Value");//基准类型A----H
                if (baseattstr == "无")
                {
                    baseattstr = null;
                }
                string mainbasematstr = maiinbasemat.GetProperties().GetEnumAsString("Value");
                object mainbasematobj = null;//这个是主基准材料状况
                if (mainbasematstr == "最好材料状况")
                {
                    mainbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.MaximumMaterialCondition;
                }
                else if (mainbasematstr == "最差材料状况")
                {
                    mainbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.LeastMaterialCondition;
                }
                else if (mainbasematstr == "不考虑特征大小")
                {
                    mainbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.RegardlessOfFeatureSize;
                }
                else if (mainbasematstr == "无")
                {
                    mainbasematobj = null;
                }
                string firstbasestr = firstrefbase.GetProperties().GetEnumAsString("Value");//第一参考基准，也就是平常说的第二参考基准
                if (firstbasestr == "无")
                {
                    firstbasestr = null;
                }
                string firstbasematstr = firstrefbasemat.GetProperties().GetEnumAsString("Value");
                object firstbasematobj = null;//这个是第一（第二）参考基准的材料特性
                if (firstbasematstr == "最好材料状况")
                {
                    firstbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.MaximumMaterialCondition;
                }
                else if (firstbasematstr == "最差材料状况")
                {
                    firstbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.LeastMaterialCondition;
                }
                else if (firstbasematstr == "不考虑特征大小")
                {
                    firstbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.RegardlessOfFeatureSize;
                }
                else if (firstbasematstr == "无")
                {
                
                firstbasematobj = null;
                }
                string secbasestr = secrefbase.GetProperties().GetEnumAsString("Value");//第二参考基准（第三）
                if (secbasestr == "无")
                {
                    secbasestr = null;

                }
                string secbasematstr = secrefbasemat.GetProperties().GetEnumAsString("Value");

                object secbasematobj = null;//这个是第二（第三）参考基准的材料特性
                if (secbasematstr == "最好材料状况")
                {
                    secbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.MaximumMaterialCondition;
                }
                else if (secbasematstr == "最差材料状况")
                {
                    secbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.LeastMaterialCondition;
                }
                else if (secbasematstr == "不考虑特征大小")
                {
                    secbasematobj = NXOpen.Annotations.DatumReferenceBuilder.DatumReferenceMaterialCondition.RegardlessOfFeatureSize;
                }
                else if (secbasematstr == "无")
                {
                    secbasematobj = null;
                
                }
                double tolvalue = double0.GetProperties().GetDouble("Value");//这个是公差值
                double zoom = double01.GetProperties().GetDouble("Value");//这个是放大缩小的因子

                int pp = framstyle.GetProperties().GetEnum("Value");
                object kuang = null;//框样式
                if (pp == 0)//单框
                {
                    kuang = NXOpen.Annotations.FeatureControlFrameBuilder.FcfFrameStyle.SingleFrame;
                }
                else if (pp == 1)//多框
                {
                    kuang = NXOpen.Annotations.FeatureControlFrameBuilder.FcfFrameStyle.CompositeFrame;
                }
                int qq = postion.GetProperties().GetEnum("Value");
                //if (qq == 0)//折线形式是选择点
                //{   
                //    Selection.MaskTriple[] msktripe = null;
                //    msktripe[0].Type = NXOpen.UF.UFConstants.UF_point_type;
                //    selection0.GetProperties().SetSelectionFilter("SelectionFilter", Selection.SelectionAction.ClearAndEnableSpecific, msktripe);
                //    //NXOpen.TaggedObject tagobj = selection0.GetProperties().GetTaggedObject("SelectedObjects");
                //}
                //else if (qq == 1)//折现形式是选择线
                //{
                //    Selection.MaskTriple[] msktripe = null;
                //    msktripe[0].Type = NXOpen.UF.UFConstants.UF_solid_type;
                //    msktripe[0].Subtype = NXOpen.UF.UFConstants.UF_all_subtype;
                //    msktripe[0].SolidBodySubtype = NXOpen.UF.UFConstants.UF_UI_SEL_FEATURE_ANY_EDGE;


                //}
                Point zhexiandian = null;
                NXOpen.TaggedObject[] tagobj00 = selection0.GetProperties().GetTaggedObjectVector("SelectedObjects");
                zhexiandian = Tag2NXObject<Point>(tagobj00[0].Tag);
                Point3d realdian = zhexiandian.Coordinates;//这个是折线点
                NXObject guanlian = null;//关联对象
                if (selection01.GetProperties().GetLogical("Enable"))
                {
                    NXOpen.TaggedObject[] tagobj1 = selection01.GetProperties().GetTaggedObjectVector("SelectedObjects");

                    guanlian = Tag2NXObject<NXObject>(tagobj1[0].Tag);
                }

                int st = ifotherbase.GetProperties().GetEnum("Value");
                if (st == 0)
                {
                    firstbasematobj = null;
                    firstbasestr = null;
                    secbasestr = null;
                    secbasematobj = null;
                }
                else if (st == 1)
                {
                    secbasestr = null;
                    secbasematobj = null;
                }
              double conlength = double02.GetProperties().GetDouble("Value");//这是短线长度。
                Selection.MaskTriple msktrp;
             //msktrp.Subtype = 
             //selection0.GetProperties().SetSelectionFilter("SelectionFilter",Selection.SelectionAction.ClearAndEnableSpecific,
              thefun.function(tolvalue.ToString(), baseattstr, firstbasestr, secbasestr, zhileixing, matcondition, mainbasematobj, firstbasematobj, secbasematobj, kuang, zoom, conlength, pt3d, realdian, guanlian);
   
            //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    public static T Tag2NXObject<T>(Tag tag)
    {
        try
        {
            object to = NXOpen.Utilities.NXObjectManager.Get(tag);
            return (T)to;
        }
        catch (System.Exception ex)
        {
            UI.GetUI().NXMessageBox.Show("Message", NXMessageBox.DialogType.Error, ex.Message);
            return default(T);
        }
    }
    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: focusNotify_cb
    //This callback is executed when any block (except the ones which receive keyboard entry such as Integer block) receives focus.
    //------------------------------------------------------------------------------
    public void focusNotify_cb(NXOpen.BlockStyler.UIBlock block, bool focus)
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: keyboardFocusNotify_cb
    //This callback is executed when block which can receive keyboard entry, receives the focus.
    //------------------------------------------------------------------------------
    public void keyboardFocusNotify_cb(NXOpen.BlockStyler.UIBlock block, bool focus)
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
}
